# The URL the site will be built for
base_url = "https://archion.github.io"

title = "Life4Zturn"
description = "余的折腾史"


# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = true

highlight_theme = "1337"

#theme = "light"
theme = "materialize"
#generate_categories_pages = true
generate_tags_pages = true

generate_rss = true

rss_limit = 20

[extra]
# Put all your custom variables here
